
class PrintPrompts:

    WELCOME = "Welcome to XYZ Hospital"
    LOGIN = "You have three attempts to login\n"
    INVALID = "Invalid username or password"
    SUCCESS = "Successful login"
    NOT_FOUND = "Not Found!!"
    APPOINTMENT_MENU = "1) More Appointment details\n2) Delete\n3) Quit\n"
    INVALID_INPUT = "Invalid input. Enter again: "
    NO_APPOINTMENTS = "No more appointments"
    NO_DOCTOR = "No more Doctors available"
    MENU = "Choose any of the options:\n1) Doctors list\n2) Appointment booking\n3) Exit"
    APPOINTMENTS = "1) Book Appointment\n2) Cancel Appointment\n3) Show Appointments\n4) Quit"
    UNAVAILABLE = "Doctor not available. Book again"
    INVALID_OPTION = "Invalid option"
    ADDED = "Appointment added\n"
    INVALID = "Invalid Input"
    ATTEMPTS = "You have three attempts to login\n"
    MAIN_MENU = "Select one option:\n1) Admin\n2) User\n3) Quit\n"
    ADMIN_MENU = "Choose any:\n1) Add a doctor\n2) Delete a doctor\n3) Quit\n"
    INVALID_CHOICE = "Invalid choice"
    LOGIN_MENU = "Choose any:\n1) Login\n2) Register\n"
    NO_ATTEMPTS = "Total attempts exhausted"
    UNABLE = "Unable to register or login"
    ERROR = "UNEXPECTED ISSUE OCCURRED. PLEASE TRY AGAIN LATER."
    APPOINTMENT_DELETED = "Appointment deleted"

class InputPrompts:
    ENTER = "Enter: "
    OPTION = "Enter options: "
    ENTER_DATE = "Enter date and time (eg- 2023-10-10 09:00 AM): "
    CANCEL = 'Which appointment do you want to cancel? '
    UNAME = "Enter username: "
    DOCTOR_ID = "Enter doctor id: "